# This is a basic workflow to help you get started with Actions

name: portal

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
     - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Deploy-Portal:
    name: Deploy Customer Portal
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1                       
      - name: Install NodeJS
        uses: actions/setup-node@v1
      - name: Install portal cli
        run: npm install -g kong-portal-cli           
      # We will push to the Kong dev portal
      - name: Deploy to dev portal
        run: |                          
          portal deploy ${{ secrets.KONG_WORKSPACE }} --preserve
        env:
          KONG_ADMIN_URL: ${{ secrets.KONG_ADDR }}
